### ISSUE TITLE
Mini-Games Crashed

### ISSUE THREAD

**Issue by flyingpianos** [IBwWG/mathildagame-bugs#104]
In the home screen, I selected "A".  When I first entered the Map, the Mini-games were available to play.  But no matter which one I clicked on, the game crashed.  (I was out of the game, at the Itch.io app "Launch" area.)  The first one I had tried was Paint Your Dreams.  After that, I tried other ones (forget the order) and the same thing happened.  (Sorry for the lack of details - I can't remember...)

**Comment by IBwWG** [comment]
Thanks, I'll check the crash report!  I'm assuming the A slot was your game from previous versions continued on here, and not a new game...

**Comment by IBwWG** [comment]
Got the crash reports.  Hey, able to crash automatically with the data sent!  Nice!

**Comment by IBwWG** [comment]
OK, I don't like what's going on here, but I seemed to have fixed it.  Please reopen this if it still occurs in the next release using your save slot A.
